version: '3.8'

services:
  video-downloader:
    build: .
    container_name: self-hosted-yt-dlp
    ports:
      - "5037:5000"
    volumes:
      - /mnt/media/Videos:/library/Videos
    restart: unless-stopped